### ISSUE TITLE
 The problem encountered during installation of the environment.

### ISSUE THREAD

**Issue by king1111sadjfoisja** [sharinka0715/semantic-gaussians#10]
Dear author!Thank you for open-sourcing such a great piece of work.
During the installation of the environment, I encountered some issues as follows:
When running command:
`pip install -r requirements.txt`
error message appeared：
```
Collecting cachetools<6.0,>=2.0.0
  Downloading https://mirrors.aliyun.com/pypi/packages/04/e6/a1551acbaa06f3e48b311329828a34bc9c51a8cfaecdeb4d03c329a1ef85/cachetools-5.4.0-py3-none-any.whl (9.5 kB)
Collecting rsa<5,>=3.1.4
  Downloading https://mirrors.aliyun.com/pypi/packages/49/97/fa78e3d2f65c02c8e1268b9aba606569fe97f6c8f7c2d74394553347c145/rsa-4.9-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading https://mirrors.aliyun.com/pypi/packages/3b/5d/63d4ae3b9daea098d5d6f5da83984853c1bbacd5dc826764b249fe119d24/requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Collecting importlib-metadata>=4.4
  Downloading https://mirrors.aliyun.com/pypi/packages/82/47/bb25ec04985d0693da478797c3d8c1092b140f3a53ccb984fbbd38affa5b/importlib_metadata-8.2.0-py3-none-any.whl (25 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow[and-cuda]==2.14.0->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow[and-cuda]==2.14.0->-r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: idna<4,>=2.5 in /home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow[and-cuda]==2.14.0->-r requirements.txt (line 1)) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow[and-cuda]==2.14.0->-r requirements.txt (line 1)) (2024.7.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow[and-cuda]==2.14.0->-r requirements.txt (line 1)) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages (from sympy->torch>=1.7->timm==0.6.13->-r requirements.txt (line 2)) (1.3.0)
Collecting zipp>=0.5
  Downloading https://mirrors.aliyun.com/pypi/packages/20/38/f5c473fe9b90c8debdd29ea68d5add0289f1936d6f923b6b9cc0b931194c/zipp-3.19.2-py3-none-any.whl (9.0 kB)
Collecting pyasn1<0.7.0,>=0.4.6
  Downloading https://mirrors.aliyun.com/pypi/packages/23/7e/5f50d07d5e70a2addbccd90ac2950f81d1edd0783630651d9268d7f1db49/pyasn1-0.6.0-py2.py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.3/85.3 kB 9.5 MB/s eta 0:00:00
Collecting oauthlib>=3.0.0
  Downloading https://mirrors.aliyun.com/pypi/packages/7e/80/cab10959dc1faead58dc8384a781dfbf93cb4d33d50988f7a69f1b7c9bbe/oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 6.2 MB/s eta 0:00:00
Building wheels for collected packages: rgb-rasterization, rgbd-rasterization, channel-rasterization, semantic-rasterization, simple-knn, segment-anything
  Building wheel for rgb-rasterization (setup.py) ... done
  Created wheel for rgb-rasterization: filename=rgb_rasterization-0.0.0-cp39-cp39-linux_x86_64.whl size=476727 sha256=417a65658772aa8808bcbef73bdce5c6352a29c7ddc9eead5e479b709b55f056
  Stored in directory: /home/gdut403/.cache/pip/wheels/7d/46/b2/146184c72d7afdb9aa3c64191ab8118efc160b73fa5bd17603
  Building wheel for rgbd-rasterization (setup.py) ... done
  Created wheel for rgbd-rasterization: filename=rgbd_rasterization-0.0.0-cp39-cp39-linux_x86_64.whl size=475821 sha256=9565b78d2a61928e0ca2f73da8d9132f21cdf51e850220aba641b7598107dd5c
  Stored in directory: /home/gdut403/.cache/pip/wheels/83/dc/4c/c137cd056da0c9a93d8b2ef1f2a1ee7d7da22c3bfed4f4799d
  Building wheel for channel-rasterization (setup.py) ... done
  Created wheel for channel-rasterization: filename=channel_rasterization-0.0.0-cp39-cp39-linux_x86_64.whl size=481445 sha256=99f566cd8195e793310dce188d85c09abc4538733b0729040c99e7843cb74308
  Stored in directory: /home/gdut403/.cache/pip/wheels/c2/4b/a9/51ebae7473537fc3adb4b5bf7c6a1eceeb32a8a8b36c777218
  Building wheel for semantic-rasterization (setup.py) ... done
  Created wheel for semantic-rasterization: filename=semantic_rasterization-0.0.0-cp39-cp39-linux_x86_64.whl size=485162 sha256=61b251c6475c3ea41c0cec9a341a3164e9c5d2256620a67aa095093ec77ef1b1
  Stored in directory: /home/gdut403/.cache/pip/wheels/c5/bf/85/2144677ba991925c4f7803bfe8608c89d1ef66a1145603e698
  Building wheel for simple-knn (setup.py) ... done
  Created wheel for simple-knn: filename=simple_knn-0.0.0-cp39-cp39-linux_x86_64.whl size=540201 sha256=11195ab727733fe91174097340049eb245d61e8c2e50cec5dab9dabfb7e9cc92
  Stored in directory: /home/gdut403/.cache/pip/wheels/32/70/0d/dd52bc1400142aa01604a0384b48f0a01b53647bf839b4fb85
  Building wheel for segment-anything (setup.py) ... done
  Created wheel for segment-anything: filename=segment_anything-1.0-py3-none-any.whl size=45596 sha256=89605ae7beee71efcab68299c961130637e06a8ab089b986c1e3c19fca91acf8
  Stored in directory: /home/gdut403/.cache/pip/wheels/13/5d/6e/1162129300a9cdc8b2fc4e86bf9e0c7adf46a74cf887341ae9
Successfully built rgb-rasterization rgbd-rasterization channel-rasterization semantic-rasterization simple-knn segment-anything
Installing collected packages: simple-knn, semantic-rasterization, segment-anything, rgbd-rasterization, rgb-rasterization, libclang, flatbuffers, channel-rasterization, antlr4-python3-runtime, zipp, wrapt, werkzeug, tifffile, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, six, scipy, pyasn1, protobuf, packaging, opt-einsum, opencv-python, omegaconf, oauthlib, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvcc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, ml-dtypes, keras, imageio, h5py, grpcio, gast, fsspec, cachetools, absl-py, rsa, requests-oauthlib, pyasn1-modules, nvidia-cusolver-cu11, nvidia-cudnn-cu11, lazy-loader, importlib-metadata, huggingface-hub, google-pasta, astunparse, tensorrt, scikit-image, markdown, google-auth, timm, google-auth-oauthlib, tensorboard, tensorflow
ERROR: Exception:
Traceback (most recent call last):
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 494, in run
    installed = install_given_reqs(
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 792, in install
    install_wheel(
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 729, in install_wheel
    _install_wheel(
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 589, in _install_wheel
    file.save()
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/zipfile.py", line 924, in read
    data = self._read1(n)
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/zipfile.py", line 1014, in _read1
    self._update_crc(data)
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/zipfile.py", line 942, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'nvidia/cudnn/lib/libcudnn_cnn_train.so.8'
```
I'm not sure why such error messages appeared or how to resolve it.
Please provide your assistance; I would be immensely grateful!

**Comment by sharinka0715** [comment]
Hi,

Sorry for hear that, but I don't think it is related to our work/requirements, so I cannot provide valuable suggestions. 

It seems that CUDNN on your environment is broken. Perhaps you did not download the complete requirements during installation.

**Comment by king1111sadjfoisja** [comment]
thanks for replying!What version of cuDNN does the project require?

**Comment by king1111sadjfoisja** [comment]
Thanks,but 
What version of cuDNN does the project require?

**Comment by sharinka0715** [comment]
> Thanks,but What version of cuDNN does the project require?

We do not require specific cuDNN versions. You just need to create a conda environment via following README.md, and it will guide you to install a suitable version of CUDA.
