### ISSUE TITLE
Regarding the resolution of the Viser visualization results

### ISSUE THREAD

**Issue by HuGhcat-code** [sharinka0715/semantic-gaussians#27]
Dear author:
Thank you for open-sourcing such a great piece of work.
However, I encountered the following issues when visualizing the Gaussian training results：
![图片](https://github.com/user-attachments/assets/7626b6dd-de06-4deb-87e0-0edec86631ec)
When I adjust the resolution of the display results（click 3x），The following error message occurred on the 3090 server：
![图片](https://github.com/user-attachments/assets/f8bc1dee-3d1b-42eb-a33c-d4465943b475)

```
Traceback (most recent call last):
  File "/home/gdut403/HK/myproject/1111semantic-gaussians-main/only_gaussians_view_viser.py", line 439, in <module>
    main(config)
  File "/home/gdut403/HK/myproject/1111semantic-gaussians-main/only_gaussians_view_viser.py", line 366, in main
    output = render(
  File "/home/gdut403/HK/myproject/1111semantic-gaussians-main/model/renderer.py", line 118, in render
    rendered_image, radii, depth = rasterizer(
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/rgbd_rasterization/__init__.py", line 221, in forward
    return rasterize_gaussians(
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/rgbd_rasterization/__init__.py", line 29, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/gdut403/anaconda3/envs/sega/lib/python3.9/site-packages/rgbd_rasterization/__init__.py", line 80, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer, depth = _C.rasterize_gaussians(*args)
RuntimeError: numel: integer multiplication overflow
```
Have you encountered a similar issue before? How should it be resolved?

**Comment by sharinka0715** [comment]
Hello,
Sorry for hear that, but I have no idea with your problem. Maybe you can refer to this issue for possible solutions.
https://github.com/sharinka0715/semantic-gaussians/issues/22#issuecomment-2434624567
