### ISSUE TITLE
Undefined symbol after installing as instructed

### ISSUE THREAD

**Issue by ziqi-ma** [sharinka0715/semantic-gaussians#5]
Hello! I am installing this repo on linux x86 with cuda 11.8, following the instructions (all libraries as specified by the environment.yml and requirements.txt). The installation is successful, but when running train.py I get this error:
```
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/ziqi/Repos/semantic-gaussians/train.py", line 11, in <module>
    from model import GaussianModel
  File "/home/ziqi/Repos/semantic-gaussians/model/__init__.py", line 2, in <module>
    from .renderer import render, render_sem, render_chn
  File "/home/ziqi/Repos/semantic-gaussians/model/renderer.py", line 14, in <module>
    from rgbd_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "/home/ziqi/anaconda3/envs/sega/lib/python3.9/site-packages/rgbd_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: /home/ziqi/anaconda3/envs/sega/lib/python3.9/site-packages/rgbd_rasterization/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl3cow11cow_deleterEPv
```
What could be causing this? Thanks!

**Comment by ziqi-ma** [comment]
Resolved by cloning with --recursive.
